name: Test wf_test

on: workflow_dispatch

jobs:
  morph:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: checkit
       run: |
        pwd
        ls -la .github/workflows
        ls -la .github/workflows/actions
        cat .github/workflows/actions/wf_test.yml
        cat /home/runner/work/actions/actions/wf_test.yml
            
     - uses: ./.github/actions/wf_test
       with:
           message: "Is this real?"
  job2:
    name: run it
    needs: morph
    runs-on: ubuntu-latest
    steps:
      - id: s1
        uses: ./.github/actions/wf_test
      - run: echo ${{ needs.morph.outputs.reply }}
