name: Test wf_test

on: workflow_dispatch

jobs:
  morph:
   runs-on: ubuntu-latest
   steps:
     - name: precheckout
       run: |
         pwd
         ls -la 
     - uses: actions/checkout@v2
     - name: postcheckout
       run: |
         pwd
         ls -la 
     - uses: ./wf_test.yml
       with:
           message: "Is this real?"
  job2:
    name: run it
    needs: morph
    runs-on: ubuntu-latest
    steps:
      - id: s1
        uses: ./wf_test.yml
      - run: echo ${{ needs.morph.outputs.reply }}
