name: Test wf_test

on: workflow_dispatch

jobs:
  morph:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: checkit
       run: ls -la .github
     - uses: ./.github/workflows/actions/wf_test.yml
       with:
           message: "Is this real?"
  job2:
    name: run it
    needs: morph
    runs-on: ubuntu-latest
    steps:
      - id: s1
        uses: ./.github/workflows/actions/wf_test.yml
      - run: echo ${{ needs.morph.outputs.reply }}
