name: Test wf_test

on:
  workflow_dispatch:

jobs:
  morph:
    - uses: hsolbrig/actions/wf_test@main
      with:
        message: "Is this real?"
  job1:
    name: run it
    needs: morph
    runs-on: ubuntu-latest
    steps:
      - id: s1
        uses: hsolbrig/actions/wf_test@main
      - run: echo ${{ needs.morph.outputs.reply }}
